sudo: required
services:
    - docker

before_install:
    - docker build -t vertigo090/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true vertigo090/react-test npm test

after_success:
    - docker build -t vertigo090/complex-client ./client
    - docker build -t vertigo090/complex-nginx ./nginx
    - docker build -t vertigo090/complex-server ./server
    - docker build -t vertigo090/complex-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push vertigo090/complex-client
    - docker push vertigo090/complex-server
    - docker push vertigo090/complex-nginx
    - docker push vertigo090/complex-worker
# deploy:
#     provider: elasticbeanstalk
#     region:
#     app:
#     env:
#     bucker_name:
#     bucket_path:
#     on:
#         branch: master
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key:
#         secure: '$AWS_SECRET_KEY'
