sudo: required
services:
    - docker

before_install:
    - docker build -t bartosz/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true bartosz/react-test npm test

after_success:
    - docker build -t bartosz/complex-client ./client
    - docker build -t bartosz/complex-nginx ./nginx
    - docker build -t bartosz/complex-server ./server
    - docker build -t bartosz/complex-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push bartosz/complex-client
    - bartosz/complex-nginx
    - bartosz/complex-nginx
    - bartosz/complex-worker
